# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #Deploy docs
      - name: Npm Install
        run: npm install
      - name: Build docs
        run: npm run docs:build
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/.vitepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # git config --global --add safe.directory /docs/.vitepress/dist
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Destination branch to push changes
          branch: gh-pages
          # Use force push to fully overwrite the destination branch
          force: true
          # We have to push from the folder where files were generated.
          # Same were the new repo was initialized in the previous step
          directory: ./docs/.vitepress/dist
